# Generated by Django 5.2.6 on 2025-09-05 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("excerpt", models.CharField(max_length=255)),
                ("fullText", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(max_length=100)),
                ("tourType", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
